name: nobes
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animated_icon_button: ^1.0.2
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter:
    sdk: flutter
  get: 4.6.5
  get_storage: ^2.1.1
  google_fonts: ^4.0.3
  http: ^0.13.5
  search_page: ^2.3.0
  translator: ^0.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
